import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:soloadventurer/features/travel/domain/models/place_activity.dart';

part 'activity_suggestion.freezed.dart';

/// A suggested activity for adding to an itinerary
///
/// Generated by the [SmartSuggestionService] based on user interests,
/// current location, weather, and other factors.
///
/// Example:
/// dart
/// final suggestion = ActivitySuggestion(
///   activity: louvreMuseum,
///   reason: 'Matches your interest in Art • Indoor activity (rain expected)',
///   score: 0.85,
/// );
///
@freezed
class ActivitySuggestion with _$ActivitySuggestion {
  const ActivitySuggestion._();

  /// Creates an activity suggestion
  ///
  /// The [activity] parameter is the place/activity being suggested.
  /// The [reason] parameter explains why this was suggested.
  /// The [score] parameter is the relevance score (0-1).
  const factory ActivitySuggestion({
    required PlaceActivity activity,
    required String reason,
    required double score,
  }) = _ActivitySuggestion;

  /// Returns true if this is a highly relevant suggestion
  bool get isHighlyRelevant => score >= 0.7;

  /// Returns true if this is a moderately relevant suggestion
  bool get isModeratelyRelevant => score >= 0.4;

  /// Returns the relevance category for UI display
  SuggestionRelevance get relevance {
    if (score >= 0.7) return SuggestionRelevance.high;
    if (score >= 0.4) return SuggestionRelevance.medium;
    return SuggestionRelevance.low;
  }
}

/// Relevance level of a suggestion
///
/// Used for UI display and filtering.
enum SuggestionRelevance {
  /// High relevance (+ score) - show prominently
  high,

  /// Medium relevance (- score) - show normally
  medium,

  /// Low relevance (< score) - show collapsed or hide
  low,
}
