import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:soloadventurer/features/travel/domain/models/itinerary_item.dart';

part 'optimization_suggestion.freezed.dart';

/// Type of optimization suggestion
///
/// Defines the category of optimization being suggested.
enum OptimizationType {
  /// Reorder items to minimize travel time between locations
  reorderForEfficiency,

  /// Group nearby activities together to reduce travel
  groupNearbyLocations,

  /// Suggest alternative times to avoid peak hours at popular attractions
  avoidPeakHours,

  /// Suggest indoor alternatives when rain is expected
  accountForWeather,

  /// Reorder items to reduce total travel time
  reduceTravelTime,
}

/// Optimization suggestion for improving an itinerary
///
/// Represents a single optimization that can be applied to an itinerary.
/// These are generated by the [ItineraryOptimizer] service based on
/// various factors like weather, location proximity, and peak hours.
///
/// Example:
/// ```dart
/// final suggestion = OptimizationSuggestion(
///   id: 'opt-1',
///   type: OptimizationType.avoidPeakHours,
///   title: 'Visit Louvre in the morning',
///   description: 'Current time (2:00 PM) is peak hours. Consider visiting at 9:00 AM.',
///   affectedItems: [louvreItem],
///   suggestedOrder: [louvreItem],
///   reasoning: 'Peak hours: 2:00 PM-4:00 PM',
///   timeSaved: Duration(hours: 2),
/// );
/// ```
@freezed
sealed class OptimizationSuggestion with _$OptimizationSuggestion {
  /// Creates an optimization suggestion
  ///
  /// The [id] parameter is a unique identifier for this suggestion.
  /// The [type] parameter is the category of optimization.
  /// The [title] parameter is a short, user-friendly title.
  /// The [description] parameter explains the optimization in detail.
  /// The [affectedItems] parameter lists items that will be changed.
  /// The [suggestedOrder] parameter is the new order for affected items.
  /// The [reasoning] parameter explains why this optimization is suggested.
  /// The [timeSaved] parameter is estimated time saved by applying this.
  /// The [costSaved] parameter is any cost savings (optional).
  const factory OptimizationSuggestion({
    required String id,
    required OptimizationType type,
    required String title,
    required String description,
    required List<ItineraryItem> affectedItems,
    required List<ItineraryItem> suggestedOrder,
    String? reasoning,
    @Default(Duration.zero) Duration timeSaved,
    double? costSaved,
  }) = _OptimizationSuggestion;

  // Private constructor for freezed
  const OptimizationSuggestion._();
}

/// Extension on [OptimizationSuggestion] for computed properties
extension OptimizationSuggestionExtension on OptimizationSuggestion {
  /// Returns the priority of this suggestion for sorting
  ///
  /// Suggestions that save more time or money have higher priority.
  int get priority {
    int score = 0;
    score += timeSaved.inMinutes;
    if (costSaved != null) score += (costSaved! * 10).round();
    return score;
  }

  /// Returns a formatted string describing the benefit
  String get benefitDescription {
    final parts = <String>[];
    if (timeSaved > Duration.zero) {
      final hours = timeSaved.inHours;
      final minutes = timeSaved.inMinutes % 60;
      if (hours > 0) {
        parts.add('${hours}h ${minutes}m saved');
      } else {
        parts.add('$minutes min saved');
      }
    }
    if (costSaved != null && costSaved! > 0) {
      parts.add('\$${costSaved!.toStringAsFixed(2)} saved');
    }
    if (parts.isEmpty) return 'Optimize schedule';
    return parts.join(' • ');
  }
}
