import 'package:freezed_annotation/freezed_annotation.dart';

import 'destination.dart';

part 'curated_list.freezed.dart';
part 'curated_list.g.dart';

/// Type of curated destination collection
enum CuratedListType {
  /// Popular destinations among solo travelers
  @JsonValue('popular_solo')
  popularSolo,

  /// Hidden gems and underrated destinations
  @JsonValue('hidden_gems')
  hiddenGems,

  /// Budget-friendly solo destinations
  @JsonValue('budget_friendly')
  budgetFriendly,

  /// Adventure destinations for solo travelers
  @JsonValue('adventure')
  adventure,

  /// Cultural and historical destinations
  @JsonValue('cultural')
  cultural,

  /// Beach and coastal destinations
  @JsonValue('beach')
  beach,

  /// Urban and city destinations
  @JsonValue('urban')
  urban,

  /// Nature and wilderness destinations
  @JsonValue('nature')
  nature,

  /// Food and culinary destinations
  @JsonValue('food')
  food,

  /// Wellness and retreat destinations
  @JsonValue('wellness')
  wellness,

  /// Seasonal or time-specific collections
  @JsonValue('seasonal')
  seasonal,

  /// Custom curated collections
  @JsonValue('custom')
  custom,
}

/// Represents a curated collection of destinations for solo travelers
///
/// Curated lists are thematic collections of destinations hand-picked by
/// travel experts or generated by the AI system. They help solo travelers
/// discover destinations that match their interests and travel style.
@freezed
class CuratedList with _$CuratedList {
  const factory CuratedList({
    /// Unique identifier for this curated list
    required String id,

    /// Display name of the curated list
    /// Example: "Hidden Gems of Southeast Asia", "Best European Cities for Solo Travel"
    required String name,

    /// Detailed description of the curated list
    /// Explains the theme and what travelers can expect
    required String description,

    /// Type/category of this curated list
    required CuratedListType type,

    /// List of destinations in this curated collection
    /// Ordered by relevance or recommendation priority
    required List<Destination> destinations,

    /// Cover/featured image for the curated list
    /// Used in cards and headers
    String? coverImageUrl,

    /// Additional images for the curated list (gallery)
    /// Can include destination preview images
    List<String>? images,

    /// Name of the curator/creator
    /// Could be "SoloAdventurer Team", "Travel Expert Name", etc.
    String? curatorName,

    /// Curator/creator profile image
    String? curatorImageUrl,

    /// Total number of destinations in this list
    /// Useful for quick display without loading destinations
    @Default(0) int destinationCount,

    /// Whether this list is featured/promoted
    /// Featured lists appear prominently in the app
    @Default(false) bool isFeatured,

    /// Order/priority for display in lists
    /// Lower values appear first
    @Default(0) int displayOrder,

    /// Tags for categorization and filtering
    /// Example: ["asia", "budget", "cultural"]
    List<String>? tags,

    /// Average safety score of destinations in this list
    /// Pre-calculated for quick filtering (1-10)
    double? averageSafetyScore,

    /// Average solo suitability score of destinations in this list
    /// Pre-calculated for quick filtering (1-10)
    double? averageSoloSuitabilityScore,

    /// Budget level range (if applicable)
    /// Example: "Budget-friendly", "Moderate to Expensive"
    String? budgetRange,

    /// Best season/time to visit destinations in this list
    /// Example: "March to May", "Year-round"
    String? bestTimeToVisit,

    /// Estimated duration recommendation
    /// Example: "7-10 days", "2 weeks"
    String? recommendedDuration,

    /// View count (popularity metric)
    @Default(0) int viewCount,

    /// Save/bookmark count (popularity metric)
    @Default(0) int saveCount,

    /// Timestamp when this curated list was created
    required DateTime createdAt,

    /// Timestamp when this curated list was last updated
    required DateTime updatedAt,

    /// Timestamp when this list was last published/featured
    DateTime? publishedAt,

    /// Whether this list is currently published and visible
    @Default(true) bool isPublished,
  }) = _CuratedList;

  factory CuratedList.fromJson(Map<String, dynamic> json) =>
      _$CuratedListFromJson(json);

  /// Returns true if the curated list has a cover image
  bool get hasCoverImage => coverImageUrl != null && coverImageUrl!.trim().isNotEmpty;

  /// Returns true if the curated list has additional gallery images
  bool get hasGalleryImages => images != null && images!.isNotEmpty;

  /// Returns true if the curated list has curator information
  bool get hasCuratorInfo => curatorName != null && curatorName!.trim().isNotEmpty;

  /// Returns true if this is a popular/featured list
  bool get isPopular => isFeatured || viewCount > 1000 || saveCount > 100;

  /// Returns true if this list is marked as a hidden gems collection
  bool get isHiddenGemsList => type == CuratedListType.hiddenGems;

  /// Returns true if this list is marked as budget-friendly
  bool get isBudgetFriendly => type == CuratedListType.budgetFriendly;

  /// Returns a formatted string with destination count
  /// Example: "12 Destinations", "1 Destination"
  String get destinationCountLabel {
    return destinationCount == 1
        ? '1 Destination'
        : '$destinationCount Destinations';
  }

  /// Returns the first few destinations as a preview
  /// Useful for showing a sneak peek before navigating to full list
  List<Destination> get previewDestinations {
    const previewCount = 3;
    if (destinations.length <= previewCount) {
      return destinations;
    }
    return destinations.sublist(0, previewCount);
  }

  /// Returns true if the list has valid, non-empty destinations
  bool get hasDestinations => destinations.isNotEmpty;

  /// Creates a copy with incremented view count
  CuratedList withIncrementedViewCount() {
    return copyWith(viewCount: viewCount + 1);
  }

  /// Creates a copy with incremented save count
  CuratedList withIncrementedSaveCount() {
    return copyWith(saveCount: saveCount + 1);
  }

  /// Creates a copy with decremented save count (when unsaved)
  CuratedList withDecrementedSaveCount() {
    return copyWith(saveCount: saveCount > 0 ? saveCount - 1 : 0);
  }

  /// Creates a copy with updated timestamp
  /// Useful when destinations or metadata are modified
  CuratedList withUpdatedTimestamp() {
    return copyWith(updatedAt: DateTime.now());
  }

  /// Returns true if safety scores are available for this list
  bool get hasSafetyScores => averageSafetyScore != null && averageSafetyScore! > 0;

  /// Returns true if solo suitability scores are available for this list
  bool get hasSoloSuitabilityScores =>
      averageSoloSuitabilityScore != null && averageSoloSuitabilityScore! > 0;

  /// Checks if this list matches a given tag
  bool matchesTag(String tag) {
    return tags?.any((t) => t.toLowerCase() == tag.toLowerCase()) ?? false;
  }

  /// Returns display type label
  String get typeLabel {
    switch (type) {
      case CuratedListType.popularSolo:
        return 'Popular Solo Destinations';
      case CuratedListType.hiddenGems:
        return 'Hidden Gems';
      case CuratedListType.budgetFriendly:
        return 'Budget-Friendly';
      case CuratedListType.adventure:
        return 'Adventure';
      case CuratedListType.cultural:
        return 'Cultural';
      case CuratedListType.beach:
        return 'Beach & Coastal';
      case CuratedListType.urban:
        return 'Urban Exploration';
      case CuratedListType.nature:
        return 'Nature & Wilderness';
      case CuratedListType.food:
        return 'Food & Culinary';
      case CuratedListType.wellness:
        return 'Wellness & Retreat';
      case CuratedListType.seasonal:
        return 'Seasonal Collection';
      case CuratedListType.custom:
        return 'Custom Collection';
    }
  }
}
