// Mocks generated by Mockito 5.4.6 from annotations
// in soloadventurer/test/features/sync/presentation/widgets/sync_pull_to_refresh_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:riverpod_annotation/riverpod_annotation.dart' as _i4;
import 'package:soloadventurer/features/sync/presentation/notifiers/manual_sync_notifier.dart'
    as _i3;
import 'package:soloadventurer/features/sync/presentation/state/manual_sync_state.dart'
    as _i2;
import 'package:state_notifier/state_notifier.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeManualSyncState_0 extends _i1.SmartFake
    implements _i2.ManualSyncState {
  _FakeManualSyncState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ManualSyncNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockManualSyncNotifier extends _i1.Mock
    implements _i3.ManualSyncNotifier {
  MockManualSyncNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Ref get ref => (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _i5.dummyValue<_i4.Ref>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i4.Ref);

  @override
  _i2.ManualSyncState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeManualSyncState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.ManualSyncState);

  @override
  set state(_i2.ManualSyncState? newState) => super.noSuchMethod(
        Invocation.setter(
          #state,
          newState,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ManualSyncState build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _FakeManualSyncState_0(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
      ) as _i2.ManualSyncState);

  @override
  _i6.Future<void> triggerSync() => (super.noSuchMethod(
        Invocation.method(
          #triggerSync,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void runBuild() => super.noSuchMethod(
        Invocation.method(
          #runBuild,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.RemoveListener listenSelf(
    void Function(
      _i2.ManualSyncState?,
      _i2.ManualSyncState,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValue: () {},
      ) as _i7.RemoveListener);

  @override
  bool updateShouldNotify(
    _i2.ManualSyncState? previous,
    _i2.ManualSyncState? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
      ) as bool);
}
