// Mocks generated by Mockito 5.4.6 from annotations
// in soloadventurer/test/features/recommendations/domain/usecases/get_personalized_recommendations_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:soloadventurer/core/failures/failures.dart' as _i5;
import 'package:soloadventurer/features/recommendations/domain/entities/recommendation.dart'
    as _i6;
import 'package:soloadventurer/features/recommendations/domain/entities/recommendation_request.dart'
    as _i7;
import 'package:soloadventurer/features/recommendations/domain/services/recommendation_service.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [RecommendationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecommendationService extends _i1.Mock
    implements _i2.RecommendationService {
  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.PersonalizedRecommendation>>>
      getPersonalizedRecommendations(_i7.RecommendationRequest? request) =>
          (super.noSuchMethod(
            Invocation.method(
              #getPersonalizedRecommendations,
              [request],
            ),
            returnValue: _i3.Future<
                _i4.Either<_i5.Failure,
                    List<_i6.PersonalizedRecommendation>>>.value(_i8.dummyValue<
                _i4.Either<_i5.Failure, List<_i6.PersonalizedRecommendation>>>(
              this,
              Invocation.method(
                #getPersonalizedRecommendations,
                [request],
              ),
            )),
            returnValueForMissingStub: _i3.Future<
                _i4.Either<_i5.Failure,
                    List<_i6.PersonalizedRecommendation>>>.value(_i8.dummyValue<
                _i4.Either<_i5.Failure, List<_i6.PersonalizedRecommendation>>>(
              this,
              Invocation.method(
                #getPersonalizedRecommendations,
                [request],
              ),
            )),
          ) as _i3.Future<
              _i4.Either<_i5.Failure, List<_i6.PersonalizedRecommendation>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.PersonalizedRecommendation>>>
      getRecommendationsForDate(
    _i7.RecommendationRequest? request,
    DateTime? specificDate,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #getRecommendationsForDate,
              [
                request,
                specificDate,
              ],
            ),
            returnValue: _i3.Future<
                _i4.Either<_i5.Failure,
                    List<_i6.PersonalizedRecommendation>>>.value(_i8.dummyValue<
                _i4.Either<_i5.Failure, List<_i6.PersonalizedRecommendation>>>(
              this,
              Invocation.method(
                #getRecommendationsForDate,
                [
                  request,
                  specificDate,
                ],
              ),
            )),
            returnValueForMissingStub: _i3.Future<
                _i4.Either<_i5.Failure,
                    List<_i6.PersonalizedRecommendation>>>.value(_i8.dummyValue<
                _i4.Either<_i5.Failure, List<_i6.PersonalizedRecommendation>>>(
              this,
              Invocation.method(
                #getRecommendationsForDate,
                [
                  request,
                  specificDate,
                ],
              ),
            )),
          ) as _i3.Future<
              _i4.Either<_i5.Failure, List<_i6.PersonalizedRecommendation>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.PersonalizedRecommendation>>>
      getCollaborativeRecommendations({
    required String? userId,
    required String? destination,
    required int? limit,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getCollaborativeRecommendations,
              [],
              {
                #userId: userId,
                #destination: destination,
                #limit: limit,
              },
            ),
            returnValue: _i3.Future<
                _i4.Either<_i5.Failure,
                    List<_i6.PersonalizedRecommendation>>>.value(_i8.dummyValue<
                _i4.Either<_i5.Failure, List<_i6.PersonalizedRecommendation>>>(
              this,
              Invocation.method(
                #getCollaborativeRecommendations,
                [],
                {
                  #userId: userId,
                  #destination: destination,
                  #limit: limit,
                },
              ),
            )),
            returnValueForMissingStub: _i3.Future<
                _i4.Either<_i5.Failure,
                    List<_i6.PersonalizedRecommendation>>>.value(_i8.dummyValue<
                _i4.Either<_i5.Failure, List<_i6.PersonalizedRecommendation>>>(
              this,
              Invocation.method(
                #getCollaborativeRecommendations,
                [],
                {
                  #userId: userId,
                  #destination: destination,
                  #limit: limit,
                },
              ),
            )),
          ) as _i3.Future<
              _i4.Either<_i5.Failure, List<_i6.PersonalizedRecommendation>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.PersonalizedRecommendation>>>
      getTrendingRecommendations({
    required String? destination,
    required int? limit,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getTrendingRecommendations,
              [],
              {
                #destination: destination,
                #limit: limit,
              },
            ),
            returnValue: _i3.Future<
                _i4.Either<_i5.Failure,
                    List<_i6.PersonalizedRecommendation>>>.value(_i8.dummyValue<
                _i4.Either<_i5.Failure, List<_i6.PersonalizedRecommendation>>>(
              this,
              Invocation.method(
                #getTrendingRecommendations,
                [],
                {
                  #destination: destination,
                  #limit: limit,
                },
              ),
            )),
            returnValueForMissingStub: _i3.Future<
                _i4.Either<_i5.Failure,
                    List<_i6.PersonalizedRecommendation>>>.value(_i8.dummyValue<
                _i4.Either<_i5.Failure, List<_i6.PersonalizedRecommendation>>>(
              this,
              Invocation.method(
                #getTrendingRecommendations,
                [],
                {
                  #destination: destination,
                  #limit: limit,
                },
              ),
            )),
          ) as _i3.Future<
              _i4.Either<_i5.Failure, List<_i6.PersonalizedRecommendation>>>);
}
