import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:soloadventurer/features/safety/domain/entities/check_in.dart';
import 'package:soloadventurer/features/safety/domain/providers/safety_usecase_providers.dart';

part 'check_in_notifier.freezed.dart';
part 'check_in_notifier.g.dart';

/// Data class for check-in state
@freezed
class CheckInData with _$CheckInData {
  const CheckInData._();

  const factory CheckInData({
    @Default([]) List<CheckIn> checkIns,
    @Default([]) List<CheckIn> upcomingCheckIns,
    CheckIn? selectedCheckIn,
  }) = _CheckInData;

  /// Whether there are any upcoming check-ins
  bool get hasUpcomingCheckIns => upcomingCheckIns.isNotEmpty;

  /// Count of check-ins due within the next hour
  int get dueSoonCount => upcomingCheckIns
      .where((checkIn) {
        final deadline = checkIn.deadline;
        if (deadline == null) return false;
        return deadline.isBefore(DateTime.now().add(const Duration(hours: 1)));
      })
      .length;

  /// Count of missed check-ins
  int get missedCount => checkIns
      .where((checkIn) => checkIn.status == CheckInStatus.missed)
      .length;

  /// Next check-in (if any)
  CheckIn? get nextCheckIn {
    if (upcomingCheckIns.isEmpty) return null;
    final sorted = List<CheckIn>.from(upcomingCheckIns);
    sorted.sort((a, b) {
      final aTime = a.scheduledTime ?? a.deadline ?? DateTime.now();
      final bTime = b.scheduledTime ?? b.deadline ?? DateTime.now();
      return aTime.compareTo(bTime);
    });
    return sorted.first;
  }
}

/// Notifier for managing check-in state
/// Handles creating, completing, scheduling, and cancelling check-ins
@riverpod
class CheckInNotifier extends _$CheckInNotifier {
  /// Load all check-ins
  Future<void> loadCheckIns() async {
    state = const AsyncLoading();
    state = await AsyncValue.guard(() async {
      final allCheckIns = await ref.read(getUpcomingCheckInsUseCaseProvider).getAllCheckIns();
      final upcoming = await ref.read(getUpcomingCheckInsUseCaseProvider)();

      return CheckInData(
        checkIns: allCheckIns,
        upcomingCheckIns: upcoming,
      );
    });
  }

  /// Load upcoming check-ins only
  Future<void> loadUpcomingCheckIns() async {
    state = const AsyncLoading();
    state = await AsyncValue.guard(() async {
      final upcoming = await ref.read(getUpcomingCheckInsUseCaseProvider)();

      return state.value?.copyWith(upcomingCheckIns: upcoming) ??
          CheckInData(upcomingCheckIns: upcoming);
    });
  }

  /// Create a manual check-in
  Future<void> createManualCheckIn({
    required String userId,
    required CheckInLocation location,
    String? statusMessage,
    List<String>? notifyContactIds,
    String? tripId,
  }) async {
    state = const AsyncLoading();

    state = await AsyncValue.guard(() async {
      final checkIn = CheckIn(
        id: '', // Will be generated by repository
        userId: userId,
        status: CheckInStatus.completed,
        scheduledTime: DateTime.now(),
        completedAt: DateTime.now(),
        location: location,
        statusMessage: statusMessage,
        notifyContactIds: notifyContactIds ?? const [],
        tripId: tripId,
        triggerType: CheckInTriggerType.manual,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      final createdCheckIn = await ref.read(createCheckInUseCaseProvider)(checkIn);

      final currentData = state.value ?? const CheckInData();
      final updatedCheckIns = [createdCheckIn, ...currentData.checkIns];
      final updatedUpcoming = currentData.upcomingCheckIns
          .where((c) => c.id != createdCheckIn.id)
          .toList();

      return currentData.copyWith(
        checkIns: updatedCheckIns,
        upcomingCheckIns: updatedUpcoming,
        selectedCheckIn: createdCheckIn,
      );
    });
  }

  /// Schedule a new check-in
  Future<void> scheduleCheckIn({
    required String userId,
    required DateTime scheduledTime,
    DateTime? deadline,
    CheckInLocation? location,
    String? statusMessage,
    List<String>? notifyContactIds,
    String? tripId,
    CheckInTriggerType? triggerType,
  }) async {
    state = const AsyncLoading();

    state = await AsyncValue.guard(() async {
      final checkIn = await ref.read(scheduleCheckInUseCaseProvider)(
        userId: userId,
        scheduledTime: scheduledTime,
        deadline: deadline,
        location: location,
        statusMessage: statusMessage,
        notifyContactIds: notifyContactIds,
        tripId: tripId,
        triggerType: triggerType,
      );

      final currentData = state.value ?? const CheckInData();
      final updatedCheckIns = [checkIn, ...currentData.checkIns];
      final updatedUpcoming = [checkIn, ...currentData.upcomingCheckIns];

      return currentData.copyWith(
        checkIns: updatedCheckIns,
        upcomingCheckIns: updatedUpcoming,
        selectedCheckIn: checkIn,
      );
    });
  }

  /// Complete a scheduled check-in
  Future<void> completeCheckIn({
    required String checkInId,
    required CheckInLocation location,
    String? statusMessage,
  }) async {
    state = const AsyncLoading();

    state = await AsyncValue.guard(() async {
      final completedCheckIn = await ref.read(completeCheckInUseCaseProvider)(
        checkInId: checkInId,
        location: location,
        statusMessage: statusMessage,
      );

      final currentData = state.value ?? const CheckInData();
      final updatedCheckIns = currentData.checkIns.map((c) {
        return c.id == checkInId ? completedCheckIn : c;
      }).toList();

      final updatedUpcoming = currentData.upcomingCheckIns
          .where((c) => c.id != checkInId)
          .toList();

      return currentData.copyWith(
        checkIns: updatedCheckIns,
        upcomingCheckIns: updatedUpcoming,
        selectedCheckIn: completedCheckIn,
      );
    });
  }

  /// Cancel a scheduled check-in
  Future<void> cancelCheckIn(String checkInId) async {
    state = const AsyncLoading();

    state = await AsyncValue.guard(() async {
      await ref.read(cancelCheckInUseCaseProvider)(checkInId);

      final currentData = state.value ?? const CheckInData();
      final cancelledCheckIn = currentData.checkIns
          .firstWhere((c) => c.id == checkInId)
          .copyWith(
            status: CheckInStatus.cancelled,
            updatedAt: DateTime.now(),
          );

      final updatedCheckIns = currentData.checkIns.map((c) {
        return c.id == checkInId ? cancelledCheckIn : c;
      }).toList();

      final updatedUpcoming = currentData.upcomingCheckIns
          .where((c) => c.id != checkInId)
          .toList();

      return currentData.copyWith(
        checkIns: updatedCheckIns,
        upcomingCheckIns: updatedUpcoming,
        selectedCheckIn: cancelledCheckIn,
      );
    });
  }

  /// Get check-ins for a specific trip
  Future<void> loadCheckInsByTrip(String tripId) async {
    state = const AsyncLoading();
    state = await AsyncValue.guard(() async {
      final tripCheckIns = await ref.read(getUpcomingCheckInsUseCaseProvider).getCheckInsByTrip(tripId);

      return state.value?.copyWith(checkIns: tripCheckIns) ??
          CheckInData(checkIns: tripCheckIns);
    });
  }

  /// Select a check-in for viewing
  void selectCheckIn(CheckIn? checkIn) {
    final currentData = state.value;
    if (currentData != null) {
      state = AsyncValue.data(currentData.copyWith(selectedCheckIn: checkIn));
    }
  }

  /// Clear the selected check-in
  void clearSelection() {
    final currentData = state.value;
    if (currentData != null) {
      state = AsyncValue.data(currentData.copyWith(selectedCheckIn: null));
    }
  }

  /// Refresh upcoming check-ins
  Future<void> refreshUpcoming() async {
    await loadUpcomingCheckIns();
  }

  @override
  AsyncValue<CheckInData> build() {
    // Don't auto-initialize - let consumers explicitly call loadCheckIns()
    // This allows for better control over when initialization happens
    return const AsyncValue.data(CheckInData());
  }
}
