import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../domain/usecases/create_check_in.dart';
import '../../domain/usecases/complete_check_in.dart';
import '../../domain/usecases/schedule_check_in.dart';
import '../../domain/usecases/cancel_check_in.dart';
import '../../domain/usecases/get_upcoming_check_ins.dart';
import '../../domain/entities/check_in.dart';
import '../state/check_in_state.dart';

/// Notifier for managing check-in state
/// Handles creating, completing, scheduling, and cancelling check-ins
class CheckInNotifier extends StateNotifier<CheckInState> {
  final CreateCheckInUseCase _createCheckIn;
  final CompleteCheckInUseCase _completeCheckIn;
  final ScheduleCheckInUseCase _scheduleCheckIn;
  final CancelCheckInUseCase _cancelCheckIn;
  final GetUpcomingCheckInsUseCase _getUpcomingCheckIns;

  CheckInNotifier({
    required CreateCheckInUseCase createCheckIn,
    required CompleteCheckInUseCase completeCheckIn,
    required ScheduleCheckInUseCase scheduleCheckIn,
    required CancelCheckInUseCase cancelCheckIn,
    required GetUpcomingCheckInsUseCase getUpcomingCheckIns,
  })  : _createCheckIn = createCheckIn,
        _completeCheckIn = completeCheckIn,
        _scheduleCheckIn = scheduleCheckIn,
        _cancelCheckIn = cancelCheckIn,
        _getUpcomingCheckIns = getUpcomingCheckIns,
        super(const CheckInState());

  /// Load all check-ins
  Future<void> loadCheckIns() async {
    if (state.isLoading) return;

    state = state.copyWith(isLoading: true, error: null);
    try {
      final allCheckIns = await _getUpcomingCheckIns.getAllCheckIns();
      final upcoming = await _getUpcomingCheckIns();

      state = state.copyWith(
        isLoading: false,
        checkIns: allCheckIns,
        upcomingCheckIns: upcoming,
        error: null,
      );
    } catch (e) {
      state = state.copyWith(
        isLoading: false,
        error: e.toString(),
      );
    }
  }

  /// Load upcoming check-ins only
  Future<void> loadUpcomingCheckIns() async {
    if (state.isLoading) return;

    state = state.copyWith(isLoading: true, error: null);
    try {
      final upcoming = await _getUpcomingCheckIns();

      state = state.copyWith(
        isLoading: false,
        upcomingCheckIns: upcoming,
        error: null,
      );
    } catch (e) {
      state = state.copyWith(
        isLoading: false,
        error: e.toString(),
      );
    }
  }

  /// Create a manual check-in
  Future<void> createManualCheckIn({
    required String userId,
    required CheckInLocation location,
    String? statusMessage,
    List<String>? notifyContactIds,
    String? tripId,
  }) async {
    if (state.isCreating) return;

    state = state.copyWith(isCreating: true, error: null);
    try {
      final checkIn = CheckIn(
        id: '', // Will be generated by repository
        userId: userId,
        status: CheckInStatus.completed,
        scheduledTime: DateTime.now(),
        completedAt: DateTime.now(),
        location: location,
        statusMessage: statusMessage,
        notifyContactIds: notifyContactIds ?? [],
        tripId: tripId,
        triggerType: CheckInTriggerType.manual,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      final createdCheckIn = await _createCheckIn(checkIn);

      final updatedCheckIns = [createdCheckIn, ...state.checkIns];
      final updatedUpcoming = state.upcomingCheckIns
          .where((c) => c.id != createdCheckIn.id)
          .toList();

      state = state.copyWith(
        isCreating: false,
        checkIns: updatedCheckIns,
        upcomingCheckIns: updatedUpcoming,
        selectedCheckIn: createdCheckIn,
        error: null,
      );
    } catch (e) {
      state = state.copyWith(
        isCreating: false,
        error: e.toString(),
      );
    }
  }

  /// Schedule a new check-in
  Future<void> scheduleCheckIn({
    required String userId,
    required DateTime scheduledTime,
    DateTime? deadline,
    CheckInLocation? location,
    String? statusMessage,
    List<String>? notifyContactIds,
    String? tripId,
    CheckInTriggerType? triggerType,
  }) async {
    if (state.isCreating) return;

    state = state.copyWith(isCreating: true, error: null);
    try {
      final checkIn = await _scheduleCheckIn(
        userId: userId,
        scheduledTime: scheduledTime,
        deadline: deadline,
        location: location,
        statusMessage: statusMessage,
        notifyContactIds: notifyContactIds,
        tripId: tripId,
        triggerType: triggerType,
      );

      final updatedCheckIns = [checkIn, ...state.checkIns];
      final updatedUpcoming = [checkIn, ...state.upcomingCheckIns];

      state = state.copyWith(
        isCreating: false,
        checkIns: updatedCheckIns,
        upcomingCheckIns: updatedUpcoming,
        selectedCheckIn: checkIn,
        error: null,
      );
    } catch (e) {
      state = state.copyWith(
        isCreating: false,
        error: e.toString(),
      );
    }
  }

  /// Complete a scheduled check-in
  Future<void> completeCheckIn({
    required String checkInId,
    required CheckInLocation location,
    String? statusMessage,
  }) async {
    if (state.isCompleting) return;

    state = state.copyWith(isCompleting: true, error: null);
    try {
      final completedCheckIn = await _completeCheckIn(
        checkInId: checkInId,
        location: location,
        statusMessage: statusMessage,
      );

      final updatedCheckIns = state.checkIns.map((c) {
        return c.id == checkInId ? completedCheckIn : c;
      }).toList();

      final updatedUpcoming =
          state.upcomingCheckIns.where((c) => c.id != checkInId).toList();

      state = state.copyWith(
        isCompleting: false,
        checkIns: updatedCheckIns,
        upcomingCheckIns: updatedUpcoming,
        selectedCheckIn: completedCheckIn,
        error: null,
      );
    } catch (e) {
      state = state.copyWith(
        isCompleting: false,
        error: e.toString(),
      );
    }
  }

  /// Cancel a scheduled check-in
  Future<void> cancelCheckIn(String checkInId) async {
    if (state.isCancelling) return;

    state = state.copyWith(isCancelling: true, error: null);
    try {
      await _cancelCheckIn(checkInId);

      // Create a cancelled version of the check-in
      final cancelledCheckIn =
          state.checkIns.firstWhere((c) => c.id == checkInId).copyWith(
                status: CheckInStatus.cancelled,
                updatedAt: DateTime.now(),
              );

      final updatedCheckIns = state.checkIns.map((c) {
        return c.id == checkInId ? cancelledCheckIn : c;
      }).toList();

      final updatedUpcoming =
          state.upcomingCheckIns.where((c) => c.id != checkInId).toList();

      state = state.copyWith(
        isCancelling: false,
        checkIns: updatedCheckIns,
        upcomingCheckIns: updatedUpcoming,
        selectedCheckIn: cancelledCheckIn,
        error: null,
      );
    } catch (e) {
      state = state.copyWith(
        isCancelling: false,
        error: e.toString(),
      );
    }
  }

  /// Get check-ins for a specific trip
  Future<void> loadCheckInsByTrip(String tripId) async {
    if (state.isLoading) return;

    state = state.copyWith(isLoading: true, error: null);
    try {
      final tripCheckIns = await _getUpcomingCheckIns.getCheckInsByTrip(tripId);

      state = state.copyWith(
        isLoading: false,
        checkIns: tripCheckIns,
        error: null,
      );
    } catch (e) {
      state = state.copyWith(
        isLoading: false,
        error: e.toString(),
      );
    }
  }

  /// Select a check-in for viewing
  void selectCheckIn(CheckIn? checkIn) {
    state = state.copyWith(selectedCheckIn: checkIn);
  }

  /// Clear the selected check-in
  void clearSelection() {
    state = state.copyWith(clearSelected: true);
  }

  /// Clear any error message
  void clearError() {
    state = state.copyWith(error: null);
  }

  /// Refresh upcoming check-ins
  Future<void> refreshUpcoming() async {
    await loadUpcomingCheckIns();
  }
}
