// Mocks generated by Mockito 5.4.6 from annotations
// in soloadventurer/test/features/offline/presentation/providers/connectivity_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:soloadventurer/features/offline/domain/services/connectivity_service.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeConnectivityStatus_0 extends _i1.SmartFake
    implements _i2.ConnectivityStatus {
  _FakeConnectivityStatus_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i2.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get debounceMs => (super.noSuchMethod(
        Invocation.getter(#debounceMs),
        returnValue: 0,
      ) as int);

  @override
  _i3.Stream<_i2.ConnectivityStatus> get connectivityStream =>
      (super.noSuchMethod(
        Invocation.getter(#connectivityStream),
        returnValue: _i3.Stream<_i2.ConnectivityStatus>.empty(),
      ) as _i3.Stream<_i2.ConnectivityStatus>);

  @override
  _i3.Future<_i2.ConnectivityStatus> checkConnectivity() => (super.noSuchMethod(
        Invocation.method(
          #checkConnectivity,
          [],
        ),
        returnValue:
            _i3.Future<_i2.ConnectivityStatus>.value(_FakeConnectivityStatus_0(
          this,
          Invocation.method(
            #checkConnectivity,
            [],
          ),
        )),
      ) as _i3.Future<_i2.ConnectivityStatus>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
