// Mocks generated by Mockito 5.4.6 from annotations
// in soloadventurer/test/features/sync/infrastructure/services/sync_service_impl_network_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:soloadventurer/features/sync/domain/services/network_connectivity.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNetworkStatus_0 extends _i1.SmartFake implements _i2.NetworkStatus {
  _FakeNetworkStatus_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NetworkConnectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkConnectivity extends _i1.Mock
    implements _i2.NetworkConnectivity {
  MockNetworkConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NetworkStatus get currentStatus => (super.noSuchMethod(
        Invocation.getter(#currentStatus),
        returnValue: _FakeNetworkStatus_0(
          this,
          Invocation.getter(#currentStatus),
        ),
      ) as _i2.NetworkStatus);

  @override
  _i3.Stream<_i2.NetworkStatus> get statusStream => (super.noSuchMethod(
        Invocation.getter(#statusStream),
        returnValue: _i3.Stream<_i2.NetworkStatus>.empty(),
      ) as _i3.Stream<_i2.NetworkStatus>);

  @override
  _i3.Stream<bool> get onOnline => (super.noSuchMethod(
        Invocation.getter(#onOnline),
        returnValue: _i3.Stream<bool>.empty(),
      ) as _i3.Stream<bool>);

  @override
  _i3.Stream<bool> get onOffline => (super.noSuchMethod(
        Invocation.getter(#onOffline),
        returnValue: _i3.Stream<bool>.empty(),
      ) as _i3.Stream<bool>);

  @override
  bool get isOnline => (super.noSuchMethod(
        Invocation.getter(#isOnline),
        returnValue: false,
      ) as bool);

  @override
  _i2.NetworkConnectionType get connectionType => (super.noSuchMethod(
        Invocation.getter(#connectionType),
        returnValue: _i2.NetworkConnectionType.none,
      ) as _i2.NetworkConnectionType);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> startMonitoring() => (super.noSuchMethod(
        Invocation.method(
          #startMonitoring,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> stopMonitoring() => (super.noSuchMethod(
        Invocation.method(
          #stopMonitoring,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
