// Mocks generated by Mockito 5.4.6 from annotations
// in soloadventurer/test/features/sync/infrastructure/services/sync_service_impl_persistence_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:soloadventurer/features/sync/domain/models/sync_operation.dart'
    as _i4;
import 'package:soloadventurer/features/sync/domain/services/sync_queue_persistence.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSyncQueuePersistenceResult_0 extends _i1.SmartFake
    implements _i2.SyncQueuePersistenceResult {
  _FakeSyncQueuePersistenceResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SyncQueuePersistence].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncQueuePersistence extends _i1.Mock
    implements _i2.SyncQueuePersistence {
  MockSyncQueuePersistence() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.SyncQueuePersistenceResult> saveQueue(
          List<_i4.SyncOperation>? queue) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveQueue,
          [queue],
        ),
        returnValue: _i3.Future<_i2.SyncQueuePersistenceResult>.value(
            _FakeSyncQueuePersistenceResult_0(
          this,
          Invocation.method(
            #saveQueue,
            [queue],
          ),
        )),
      ) as _i3.Future<_i2.SyncQueuePersistenceResult>);

  @override
  _i3.Future<List<_i4.SyncOperation>> loadQueue() => (super.noSuchMethod(
        Invocation.method(
          #loadQueue,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.SyncOperation>>.value(<_i4.SyncOperation>[]),
      ) as _i3.Future<List<_i4.SyncOperation>>);

  @override
  _i3.Future<_i2.SyncQueuePersistenceResult> clearQueue() =>
      (super.noSuchMethod(
        Invocation.method(
          #clearQueue,
          [],
        ),
        returnValue: _i3.Future<_i2.SyncQueuePersistenceResult>.value(
            _FakeSyncQueuePersistenceResult_0(
          this,
          Invocation.method(
            #clearQueue,
            [],
          ),
        )),
      ) as _i3.Future<_i2.SyncQueuePersistenceResult>);

  @override
  _i3.Future<bool> removeOperation(String? operationId) => (super.noSuchMethod(
        Invocation.method(
          #removeOperation,
          [operationId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> hasPersistedOperations() => (super.noSuchMethod(
        Invocation.method(
          #hasPersistedOperations,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<int> getOperationCount() => (super.noSuchMethod(
        Invocation.method(
          #getOperationCount,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}
