// Mocks generated by Mockito 5.4.6 from annotations
// in soloadventurer/test/features/recommendations/domain/repositories/recommendation_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:soloadventurer/features/recommendations/data/datasources/recommendation_local_data_source.dart'
    as _i3;
import 'package:soloadventurer/features/recommendations/domain/entities/recommendation.dart'
    as _i2;
import 'package:soloadventurer/features/recommendations/domain/entities/recommendation_request.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePersonalizedRecommendation_0 extends _i1.SmartFake
    implements _i2.PersonalizedRecommendation {
  _FakePersonalizedRecommendation_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RecommendationLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecommendationLocalDataSource extends _i1.Mock
    implements _i3.RecommendationLocalDataSource {
  @override
  _i4.Future<_i2.PersonalizedRecommendation> saveRecommendation(
    String? userId,
    _i2.PersonalizedRecommendation? recommendation,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRecommendation,
          [
            userId,
            recommendation,
          ],
        ),
        returnValue: _i4.Future<_i2.PersonalizedRecommendation>.value(
            _FakePersonalizedRecommendation_0(
          this,
          Invocation.method(
            #saveRecommendation,
            [
              userId,
              recommendation,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.PersonalizedRecommendation>.value(
                _FakePersonalizedRecommendation_0(
          this,
          Invocation.method(
            #saveRecommendation,
            [
              userId,
              recommendation,
            ],
          ),
        )),
      ) as _i4.Future<_i2.PersonalizedRecommendation>);

  @override
  _i4.Future<List<_i2.PersonalizedRecommendation>> getSavedRecommendations(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSavedRecommendations,
          [userId],
        ),
        returnValue: _i4.Future<List<_i2.PersonalizedRecommendation>>.value(
            <_i2.PersonalizedRecommendation>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i2.PersonalizedRecommendation>>.value(
                <_i2.PersonalizedRecommendation>[]),
      ) as _i4.Future<List<_i2.PersonalizedRecommendation>>);

  @override
  _i4.Future<void> dismissRecommendation(
    String? userId,
    String? recommendationId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #dismissRecommendation,
          [
            userId,
            recommendationId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> recordFeedback(
    String? recommendationId,
    _i5.RecommendationFeedback? feedback,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordFeedback,
          [
            recommendationId,
            feedback,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Set<String>> getDismissedRecommendations(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDismissedRecommendations,
          [userId],
        ),
        returnValue: _i4.Future<Set<String>>.value(<String>{}),
        returnValueForMissingStub: _i4.Future<Set<String>>.value(<String>{}),
      ) as _i4.Future<Set<String>>);

  @override
  _i4.Future<int> clearOldDismissals({
    required String? userId,
    required Duration? olderThan,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearOldDismissals,
          [],
          {
            #userId: userId,
            #olderThan: olderThan,
          },
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
}
