import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../domain/models/curated_list.dart';
import '../../application/providers/curated_lists_provider.dart';
import '../widgets/curated_list_card.dart';

/// Screen displaying all curated destination collections.
///
/// This screen shows thematic collections of destinations hand-picked by
/// travel experts or generated by AI. Features include:
/// - Featured/hero section for highlighted lists
/// - Grid of curated list cards
/// - Filter by list type (popular, hidden gems, budget, adventure, etc.)
/// - Pull-to-refresh functionality
/// - Loading, error, and empty states
///
/// The screen integrates with [CuratedListsProvider] for data management.
class CuratedListsScreen extends ConsumerStatefulWidget {
  /// Creates a new [CuratedListsScreen]
  const CuratedListsScreen({super.key});

  /// Route name for navigation
  static const String routeName = '/curated-lists';

  @override
  ConsumerState<CuratedListsScreen> createState() =>
      _CuratedListsScreenState();
}

class _CuratedListsScreenState extends ConsumerState<CuratedListsScreen> {
  /// Selected filter for curated lists
  CuratedListFilter _selectedFilter = CuratedListFilter.all;

  @override
  void initState() {
    super.initState();
    // Initial load is handled automatically by the provider
  }

  /// Refresh curated lists
  Future<void> _refreshLists() async {
    final curatedListsNotifier = ref.read(curatedListsProvider.notifier);

    try {
      await curatedListsNotifier.refresh();
    } catch (error) {
      // Error is handled in the provider's state
    }
  }

  /// Navigate to curated list detail
  void _navigateToListDetail(CuratedList curatedList) {
    // TODO: Implement navigation in subtask 6.1
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text('Opening ${curatedList.name}'),
        duration: const Duration(seconds: 1),
      ),
    );
  }

  /// Get curated lists based on selected filter
  List<CuratedList> _getFilteredList(List<CuratedList> allLists) {
    switch (_selectedFilter) {
      case CuratedListFilter.featured:
        return allLists.where((list) => list.isFeatured).toList();
      case CuratedListFilter.popularSolo:
        return allLists.where((list) => list.type == CuratedListType.popularSolo).toList();
      case CuratedListFilter.hiddenGems:
        return allLists.where((list) => list.type == CuratedListType.hiddenGems).toList();
      case CuratedListFilter.budgetFriendly:
        return allLists.where((list) => list.type == CuratedListType.budgetFriendly).toList();
      case CuratedListFilter.adventure:
        return allLists.where((list) => list.type == CuratedListType.adventure).toList();
      case CuratedListFilter.cultural:
        return allLists.where((list) => list.type == CuratedListType.cultural).toList();
      case CuratedListFilter.beach:
        return allLists.where((list) => list.type == CuratedListType.beach).toList();
      case CuratedListFilter.urban:
        return allLists.where((list) => list.type == CuratedListType.urban).toList();
      case CuratedListFilter.nature:
        return allLists.where((list) => list.type == CuratedListType.nature).toList();
      case CuratedListFilter.food:
        return allLists.where((list) => list.type == CuratedListType.food).toList();
      case CuratedListFilter.wellness:
        return allLists.where((list) => list.type == CuratedListType.wellness).toList();
      case CuratedListFilter.all:
      default:
        return allLists;
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final curatedListsState = ref.watch(curatedListsProvider);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Curated Collections'),
        actions: [
          // Filter button
          PopupMenuButton<CuratedListFilter>(
            icon: const Icon(Icons.filter_list),
            onSelected: (filter) {
              setState(() {
                _selectedFilter = filter;
              });
            },
            itemBuilder: (context) => [
              PopupMenuItem(
                value: CuratedListFilter.all,
                child: _buildFilterMenuItem(
                  context,
                  CuratedListFilter.all,
                  'All Collections',
                  Icons.apps,
                ),
              ),
              PopupMenuItem(
                value: CuratedListFilter.featured,
                child: _buildFilterMenuItem(
                  context,
                  CuratedListFilter.featured,
                  'Featured',
                  Icons.star,
                ),
              ),
              PopupMenuItem(
                value: CuratedListFilter.popularSolo,
                child: _buildFilterMenuItem(
                  context,
                  CuratedListFilter.popularSolo,
                  'Popular Solo',
                  Icons.trending_up,
                ),
              ),
              PopupMenuItem(
                value: CuratedListFilter.hiddenGems,
                child: _buildFilterMenuItem(
                  context,
                  CuratedListFilter.hiddenGems,
                  'Hidden Gems',
                  Icons.diamond,
                ),
              ),
              PopupMenuItem(
                value: CuratedListFilter.budgetFriendly,
                child: _buildFilterMenuItem(
                  context,
                  CuratedListFilter.budgetFriendly,
                  'Budget-Friendly',
                  Icons.attach_money,
                ),
              ),
              PopupMenuItem(
                value: CuratedListFilter.adventure,
                child: _buildFilterMenuItem(
                  context,
                  CuratedListFilter.adventure,
                  'Adventure',
                  Icons.hiking,
                ),
              ),
              PopupMenuItem(
                value: CuratedListFilter.cultural,
                child: _buildFilterMenuItem(
                  context,
                  CuratedListFilter.cultural,
                  'Cultural',
                  Icons.museum,
                ),
              ),
              PopupMenuItem(
                value: CuratedListFilter.beach,
                child: _buildFilterMenuItem(
                  context,
                  CuratedListFilter.beach,
                  'Beach',
                  Icons.beach_access,
                ),
              ),
              PopupMenuItem(
                value: CuratedListFilter.urban,
                child: _buildFilterMenuItem(
                  context,
                  CuratedListFilter.urban,
                  'Urban',
                  Icons.location_city,
                ),
              ),
              PopupMenuItem(
                value: CuratedListFilter.nature,
                child: _buildFilterMenuItem(
                  context,
                  CuratedListFilter.nature,
                  'Nature',
                  Icons.park,
                ),
              ),
              PopupMenuItem(
                value: CuratedListFilter.food,
                child: _buildFilterMenuItem(
                  context,
                  CuratedListFilter.food,
                  'Food',
                  Icons.restaurant,
                ),
              ),
              PopupMenuItem(
                value: CuratedListFilter.wellness,
                child: _buildFilterMenuItem(
                  context,
                  CuratedListFilter.wellness,
                  'Wellness',
                  Icons.spa,
                ),
              ),
            ],
          ),
        ],
      ),
      body: curatedListsState.when(
        data: (state) {
          final filteredLists = _getFilteredList(state.curatedLists);

          // Empty state
          if (filteredLists.isEmpty) {
            return _buildEmptyState(theme);
          }

          // Lists with featured section and grid
          return RefreshIndicator(
            onRefresh: _refreshLists,
            child: CustomScrollView(
              slivers: [
                // Featured section (if showing all lists and featured lists exist)
                if (_selectedFilter == CuratedListFilter.all &&
                    state.featuredLists.isNotEmpty)
                  SliverToBoxAdapter(
                    child: _buildFeaturedSection(theme, state.featuredLists),
                  ),

                // All lists grid
                SliverPadding(
                  padding: const EdgeInsets.all(16),
                  sliver: SliverGrid(
                    gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                      crossAxisCount: 2,
                      crossAxisSpacing: 16,
                      mainAxisSpacing: 16,
                      childAspectRatio: 0.85,
                    ),
                    delegate: SliverChildBuilderDelegate(
                      (context, index) {
                        final curatedList = filteredLists[index];
                        return CuratedListCard(
                          curatedList: curatedList,
                          onTap: () => _navigateToListDetail(curatedList),
                        );
                      },
                      childCount: filteredLists.length,
                    ),
                  ),
                ),
              ],
            ),
          );
        },
        loading: () => const Center(
          child: CircularProgressIndicator(),
        ),
        error: (error, stackTrace) => _buildErrorState(theme, error),
      ),
    );
  }

  /// Build the featured section with horizontal scrolling
  Widget _buildFeaturedSection(ThemeData theme, List<CuratedList> featuredLists) {
    return Container(
      padding: const EdgeInsets.symmetric(vertical: 16),
      decoration: BoxDecoration(
        color: theme.colorScheme.primaryContainer,
        border: Border(
          bottom: BorderSide(
            color: theme.dividerColor,
            width: 1,
          ),
        ),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16),
            child: Row(
              children: [
                Icon(
                  Icons.star,
                  color: theme.colorScheme.primary,
                ),
                const SizedBox(width: 8),
                Text(
                  'Featured Collections',
                  style: theme.textTheme.titleLarge?.copyWith(
                    color: theme.colorScheme.onPrimaryContainer,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 12),
          SizedBox(
            height: 320,
            child: ListView.builder(
              scrollDirection: Axis.horizontal,
              padding: const EdgeInsets.symmetric(horizontal: 16),
              itemCount: featuredLists.length,
              itemBuilder: (context, index) {
                final curatedList = featuredLists[index];
                return SizedBox(
                  width: 280,
                  child: Padding(
                    padding: const EdgeInsets.only(right: 16),
                    child: CuratedListCard(
                      curatedList: curatedList,
                      onTap: () => _navigateToListDetail(curatedList),
                    ),
                  ),
                );
              },
            ),
          ),
        ],
      ),
    );
  }

  /// Build empty state widget
  Widget _buildEmptyState(ThemeData theme) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(32),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(
              Icons.collections_bookmark,
              size: 64,
              color: theme.colorScheme.onSurfaceVariant,
            ),
            const SizedBox(height: 16),
            Text(
              'No curated collections found',
              style: theme.textTheme.titleLarge?.copyWith(
                color: theme.colorScheme.onSurfaceVariant,
              ),
            ),
            const SizedBox(height: 8),
            Text(
              _getEmptyStateMessage(),
              style: theme.textTheme.bodyMedium?.copyWith(
                color: theme.colorScheme.onSurfaceVariant,
              ),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 24),
            ElevatedButton.icon(
              onPressed: _refreshLists,
              icon: const Icon(Icons.refresh),
              label: const Text('Refresh'),
            ),
          ],
        ),
      ),
    );
  }

  /// Build error state widget
  Widget _buildErrorState(ThemeData theme, Object error) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(32),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(
              Icons.error_outline,
              size: 64,
              color: theme.colorScheme.error,
            ),
            const SizedBox(height: 16),
            Text(
              'Something went wrong',
              style: theme.textTheme.titleLarge?.copyWith(
                color: theme.colorScheme.error,
              ),
            ),
            const SizedBox(height: 8),
            Text(
              error.toString(),
              style: theme.textTheme.bodyMedium?.copyWith(
                color: theme.colorScheme.onSurfaceVariant,
              ),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 24),
            ElevatedButton.icon(
              onPressed: _refreshLists,
              icon: const Icon(Icons.refresh),
              label: const Text('Try Again'),
            ),
          ],
        ),
      ),
    );
  }

  /// Build filter menu item
  Widget _buildFilterMenuItem(
    BuildContext context,
    CuratedListFilter filter,
    String label,
    IconData icon,
  ) {
    final theme = Theme.of(context);
    final isSelected = _selectedFilter == filter;

    return Row(
      children: [
        Icon(
          icon,
          size: 20,
          color: isSelected ? theme.colorScheme.primary : null,
        ),
        const SizedBox(width: 12),
        Text(
          label,
          style: TextStyle(
            color: isSelected ? theme.colorScheme.primary : null,
            fontWeight: isSelected ? FontWeight.bold : null,
          ),
        ),
        if (isSelected) ...[
          const Spacer(),
          Icon(
            Icons.check,
            size: 20,
            color: theme.colorScheme.primary,
          ),
        ],
      ],
    );
  }

  /// Get empty state message based on selected filter
  String _getEmptyStateMessage() {
    switch (_selectedFilter) {
      case CuratedListFilter.featured:
        return 'No featured collections at the moment. '
            'Check back later for new highlights!';
      case CuratedListFilter.popularSolo:
        return 'No popular solo collections found. '
            'Try selecting "All Collections" to see more options.';
      case CuratedListFilter.hiddenGems:
        return 'No hidden gem collections found. '
            'Explore other categories or check back soon!';
      case CuratedListFilter.budgetFriendly:
        return 'No budget-friendly collections found. '
            'Try other categories to find destinations that fit your style.';
      case CuratedListFilter.adventure:
        return 'No adventure collections found. '
            'Check other categories for exciting destinations!';
      case CuratedListFilter.cultural:
        return 'No cultural collections found. '
            'Explore other categories to discover rich experiences!';
      case CuratedListFilter.beach:
        return 'No beach collections found. '
            'Browse other categories for sunny destinations!';
      case CuratedListFilter.urban:
        return 'No urban collections found. '
            'Check other categories for city adventures!';
      case CuratedListFilter.nature:
        return 'No nature collections found. '
            'Explore other categories for wilderness destinations!';
      case CuratedListFilter.food:
        return 'No food collections found. '
            'Try other categories for culinary experiences!';
      case CuratedListFilter.wellness:
        return 'No wellness collections found. '
            'Browse other categories for retreat destinations!';
      case CuratedListFilter.all:
      default:
        return 'No curated collections available at the moment. '
            'Our travel experts are curating new collections for you!';
    }
  }
}

/// Filter options for curated lists
enum CuratedListFilter {
  /// Show all curated lists
  all,

  /// Show only featured lists
  featured,

  /// Show only popular solo destinations
  popularSolo,

  /// Show only hidden gems collections
  hiddenGems,

  /// Show only budget-friendly collections
  budgetFriendly,

  /// Show only adventure collections
  adventure,

  /// Show only cultural collections
  cultural,

  /// Show only beach collections
  beach,

  /// Show only urban collections
  urban,

  /// Show only nature collections
  nature,

  /// Show only food collections
  food,

  /// Show only wellness collections
  wellness,
}
