// Mocks generated by Mockito 5.4.6 from annotations
// in soloadventurer/test/features/sync/presentation/notifiers/conflict_resolution_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:soloadventurer/features/core/domain/services/logging_service.dart'
    as _i12;
import 'package:soloadventurer/features/sync/domain/entities/sync_entity_type.dart'
    as _i11;
import 'package:soloadventurer/features/sync/domain/models/conflict_info.dart'
    as _i7;
import 'package:soloadventurer/features/sync/domain/models/conflict_resolution.dart'
    as _i3;
import 'package:soloadventurer/features/sync/domain/models/entity_version.dart'
    as _i4;
import 'package:soloadventurer/features/sync/domain/models/sync_operation.dart'
    as _i9;
import 'package:soloadventurer/features/sync/domain/models/sync_status.dart'
    as _i10;
import 'package:soloadventurer/features/sync/domain/services/conflict_resolver.dart'
    as _i2;
import 'package:soloadventurer/features/sync/domain/services/sync_service.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeConflictResolutionConfig_0 extends _i1.SmartFake
    implements _i2.ConflictResolutionConfig {
  _FakeConflictResolutionConfig_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConflictResolution_1 extends _i1.SmartFake
    implements _i3.ConflictResolution {
  _FakeConflictResolution_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatchResolutionResult_2 extends _i1.SmartFake
    implements _i3.BatchResolutionResult {
  _FakeBatchResolutionResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMergeResult_3 extends _i1.SmartFake implements _i3.MergeResult {
  _FakeMergeResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEntityVersion_4 extends _i1.SmartFake implements _i4.EntityVersion {
  _FakeEntityVersion_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncQueueConfig_5 extends _i1.SmartFake
    implements _i5.SyncQueueConfig {
  _FakeSyncQueueConfig_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncResult_6 extends _i1.SmartFake implements _i5.SyncResult {
  _FakeSyncResult_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ConflictResolver].
///
/// See the documentation for Mockito's code generation for more information.
class MockConflictResolver extends _i1.Mock implements _i2.ConflictResolver {
  MockConflictResolver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ConflictResolutionConfig get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: _FakeConflictResolutionConfig_0(
          this,
          Invocation.getter(#config),
        ),
      ) as _i2.ConflictResolutionConfig);

  @override
  void updateConfig(_i2.ConflictResolutionConfig? config) => super.noSuchMethod(
        Invocation.method(
          #updateConfig,
          [config],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<_i3.ConflictResolution> resolveConflict({
    required _i7.ConflictInfo? conflict,
    _i3.ConflictResolutionStrategy? strategy,
    _i3.ManualResolutionChoice? userChoice,
    Map<String, dynamic>? userData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveConflict,
          [],
          {
            #conflict: conflict,
            #strategy: strategy,
            #userChoice: userChoice,
            #userData: userData,
          },
        ),
        returnValue:
            _i6.Future<_i3.ConflictResolution>.value(_FakeConflictResolution_1(
          this,
          Invocation.method(
            #resolveConflict,
            [],
            {
              #conflict: conflict,
              #strategy: strategy,
              #userChoice: userChoice,
              #userData: userData,
            },
          ),
        )),
      ) as _i6.Future<_i3.ConflictResolution>);

  @override
  _i6.Future<_i3.BatchResolutionResult> resolveMultipleConflicts({
    required List<_i7.ConflictInfo>? conflicts,
    List<_i3.ConflictResolutionStrategy>? strategies,
    List<_i3.ManualResolutionChoice>? userChoices,
    List<Map<String, dynamic>?>? userDataList,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveMultipleConflicts,
          [],
          {
            #conflicts: conflicts,
            #strategies: strategies,
            #userChoices: userChoices,
            #userDataList: userDataList,
          },
        ),
        returnValue: _i6.Future<_i3.BatchResolutionResult>.value(
            _FakeBatchResolutionResult_2(
          this,
          Invocation.method(
            #resolveMultipleConflicts,
            [],
            {
              #conflicts: conflicts,
              #strategies: strategies,
              #userChoices: userChoices,
              #userDataList: userDataList,
            },
          ),
        )),
      ) as _i6.Future<_i3.BatchResolutionResult>);

  @override
  _i6.Future<_i3.ConflictResolution> resolveWithLastWriteWins({
    required _i7.ConflictInfo? conflict,
    bool? preferLocal = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveWithLastWriteWins,
          [],
          {
            #conflict: conflict,
            #preferLocal: preferLocal,
          },
        ),
        returnValue:
            _i6.Future<_i3.ConflictResolution>.value(_FakeConflictResolution_1(
          this,
          Invocation.method(
            #resolveWithLastWriteWins,
            [],
            {
              #conflict: conflict,
              #preferLocal: preferLocal,
            },
          ),
        )),
      ) as _i6.Future<_i3.ConflictResolution>);

  @override
  _i6.Future<_i3.ConflictResolution> resolveManually({
    required _i7.ConflictInfo? conflict,
    required _i3.ManualResolutionChoice? userChoice,
    Map<String, dynamic>? customData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveManually,
          [],
          {
            #conflict: conflict,
            #userChoice: userChoice,
            #customData: customData,
          },
        ),
        returnValue:
            _i6.Future<_i3.ConflictResolution>.value(_FakeConflictResolution_1(
          this,
          Invocation.method(
            #resolveManually,
            [],
            {
              #conflict: conflict,
              #userChoice: userChoice,
              #customData: customData,
            },
          ),
        )),
      ) as _i6.Future<_i3.ConflictResolution>);

  @override
  _i6.Future<_i3.ConflictResolution> resolveWithAutomaticMerge(
          {required _i7.ConflictInfo? conflict}) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveWithAutomaticMerge,
          [],
          {#conflict: conflict},
        ),
        returnValue:
            _i6.Future<_i3.ConflictResolution>.value(_FakeConflictResolution_1(
          this,
          Invocation.method(
            #resolveWithAutomaticMerge,
            [],
            {#conflict: conflict},
          ),
        )),
      ) as _i6.Future<_i3.ConflictResolution>);

  @override
  _i3.ConflictResolutionStrategy recommendStrategy(
          {required _i7.ConflictInfo? conflict}) =>
      (super.noSuchMethod(
        Invocation.method(
          #recommendStrategy,
          [],
          {#conflict: conflict},
        ),
        returnValue: _i3.ConflictResolutionStrategy.lastWriteWins,
      ) as _i3.ConflictResolutionStrategy);

  @override
  bool canMergeAutomatically({required _i7.ConflictInfo? conflict}) =>
      (super.noSuchMethod(
        Invocation.method(
          #canMergeAutomatically,
          [],
          {#conflict: conflict},
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.MergeResult attemptMerge({
    required Map<String, dynamic>? localData,
    required Map<String, dynamic>? remoteData,
    List<String>? protectedFields = const [],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #attemptMerge,
          [],
          {
            #localData: localData,
            #remoteData: remoteData,
            #protectedFields: protectedFields,
          },
        ),
        returnValue: _FakeMergeResult_3(
          this,
          Invocation.method(
            #attemptMerge,
            [],
            {
              #localData: localData,
              #remoteData: remoteData,
              #protectedFields: protectedFields,
            },
          ),
        ),
      ) as _i3.MergeResult);

  @override
  _i4.EntityVersion createResolvedVersion({
    required _i7.ConflictInfo? conflict,
    required _i3.ConflictResolutionStrategy? strategy,
    _i4.EntityVersion? baseVersion,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createResolvedVersion,
          [],
          {
            #conflict: conflict,
            #strategy: strategy,
            #baseVersion: baseVersion,
          },
        ),
        returnValue: _FakeEntityVersion_4(
          this,
          Invocation.method(
            #createResolvedVersion,
            [],
            {
              #conflict: conflict,
              #strategy: strategy,
              #baseVersion: baseVersion,
            },
          ),
        ),
      ) as _i4.EntityVersion);

  @override
  bool validateResolutionData({
    required String? entityType,
    required Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateResolutionData,
          [],
          {
            #entityType: entityType,
            #data: data,
          },
        ),
        returnValue: false,
      ) as bool);

  @override
  String generateResolutionDescription(
          {required _i3.ConflictResolution? resolution}) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateResolutionDescription,
          [],
          {#resolution: resolution},
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #generateResolutionDescription,
            [],
            {#resolution: resolution},
          ),
        ),
      ) as String);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i5.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i9.SyncOperation> get queue => (super.noSuchMethod(
        Invocation.getter(#queue),
        returnValue: <_i9.SyncOperation>[],
      ) as List<_i9.SyncOperation>);

  @override
  int get queueSize => (super.noSuchMethod(
        Invocation.getter(#queueSize),
        returnValue: 0,
      ) as int);

  @override
  bool get isProcessing => (super.noSuchMethod(
        Invocation.getter(#isProcessing),
        returnValue: false,
      ) as bool);

  @override
  _i10.SyncOperationStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i10.SyncOperationStatus.idle,
      ) as _i10.SyncOperationStatus);

  @override
  _i6.Stream<_i10.SyncOperationStatus> get statusStream => (super.noSuchMethod(
        Invocation.getter(#statusStream),
        returnValue: _i6.Stream<_i10.SyncOperationStatus>.empty(),
      ) as _i6.Stream<_i10.SyncOperationStatus>);

  @override
  _i6.Stream<List<_i9.SyncOperation>> get queueStream => (super.noSuchMethod(
        Invocation.getter(#queueStream),
        returnValue: _i6.Stream<List<_i9.SyncOperation>>.empty(),
      ) as _i6.Stream<List<_i9.SyncOperation>>);

  @override
  _i5.SyncQueueConfig get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: _FakeSyncQueueConfig_5(
          this,
          Invocation.getter(#config),
        ),
      ) as _i5.SyncQueueConfig);

  @override
  _i6.Future<bool> enqueueOperation(_i9.SyncOperation? operation) =>
      (super.noSuchMethod(
        Invocation.method(
          #enqueueOperation,
          [operation],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<int> enqueueOperations(List<_i9.SyncOperation>? operations) =>
      (super.noSuchMethod(
        Invocation.method(
          #enqueueOperations,
          [operations],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<bool> removeOperation(String? operationId) => (super.noSuchMethod(
        Invocation.method(
          #removeOperation,
          [operationId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> clearQueue() => (super.noSuchMethod(
        Invocation.method(
          #clearQueue,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i5.SyncResult> processQueue() => (super.noSuchMethod(
        Invocation.method(
          #processQueue,
          [],
        ),
        returnValue: _i6.Future<_i5.SyncResult>.value(_FakeSyncResult_6(
          this,
          Invocation.method(
            #processQueue,
            [],
          ),
        )),
      ) as _i6.Future<_i5.SyncResult>);

  @override
  _i6.Future<_i5.SyncResult> processBatch({int? maxBatchSize}) =>
      (super.noSuchMethod(
        Invocation.method(
          #processBatch,
          [],
          {#maxBatchSize: maxBatchSize},
        ),
        returnValue: _i6.Future<_i5.SyncResult>.value(_FakeSyncResult_6(
          this,
          Invocation.method(
            #processBatch,
            [],
            {#maxBatchSize: maxBatchSize},
          ),
        )),
      ) as _i6.Future<_i5.SyncResult>);

  @override
  _i6.Future<int> retryFailedOperations() => (super.noSuchMethod(
        Invocation.method(
          #retryFailedOperations,
          [],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  List<_i9.SyncOperation> getOperationsByType(
          _i11.SyncEntityType? entityType) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOperationsByType,
          [entityType],
        ),
        returnValue: <_i9.SyncOperation>[],
      ) as List<_i9.SyncOperation>);

  @override
  List<_i9.SyncOperation> getOperationsByOperationType(
          _i9.SyncOperationType? operationType) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOperationsByOperationType,
          [operationType],
        ),
        returnValue: <_i9.SyncOperation>[],
      ) as List<_i9.SyncOperation>);

  @override
  List<_i9.SyncOperation> getOperationsForEntity(String? entityId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOperationsForEntity,
          [entityId],
        ),
        returnValue: <_i9.SyncOperation>[],
      ) as List<_i9.SyncOperation>);

  @override
  void pauseProcessing() => super.noSuchMethod(
        Invocation.method(
          #pauseProcessing,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resumeProcessing() => super.noSuchMethod(
        Invocation.method(
          #resumeProcessing,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateConfig(_i5.SyncQueueConfig? config) => super.noSuchMethod(
        Invocation.method(
          #updateConfig,
          [config],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LoggingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoggingService extends _i1.Mock implements _i12.LoggingService {
  MockLoggingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void logStateTransition({
    required String? feature,
    required String? fromState,
    required String? toState,
    Map<String, dynamic>? metadata,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logStateTransition,
          [],
          {
            #feature: feature,
            #fromState: fromState,
            #toState: toState,
            #metadata: metadata,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logError({
    required String? feature,
    required String? error,
    String? code,
    Map<String, dynamic>? metadata,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logError,
          [],
          {
            #feature: feature,
            #error: error,
            #code: code,
            #metadata: metadata,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logAuthEvent({
    required String? event,
    required String? status,
    Map<String, dynamic>? metadata,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logAuthEvent,
          [],
          {
            #event: event,
            #status: status,
            #metadata: metadata,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logTokenEvent({
    required String? event,
    required String? status,
    Map<String, dynamic>? metadata,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logTokenEvent,
          [],
          {
            #event: event,
            #status: status,
            #metadata: metadata,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logTokenRotation({
    required Object? oldSession,
    required Object? newSession,
    String? reason,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logTokenRotation,
          [],
          {
            #oldSession: oldSession,
            #newSession: newSession,
            #reason: reason,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logTokenBlacklist({
    required String? token,
    required String? reason,
    DateTime? expiryTime,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logTokenBlacklist,
          [],
          {
            #token: token,
            #reason: reason,
            #expiryTime: expiryTime,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logTokenRefresh({
    required bool? success,
    String? error,
    int? attemptNumber = 1,
    Map<String, dynamic>? additionalInfo,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logTokenRefresh,
          [],
          {
            #success: success,
            #error: error,
            #attemptNumber: attemptNumber,
            #additionalInfo: additionalInfo,
          },
        ),
        returnValueForMissingStub: null,
      );
}
