// Mocks generated by Mockito 5.4.6 from annotations
// in soloadventurer/test/features/sync/presentation/notifiers/sync_state_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:soloadventurer/features/core/domain/services/logging_service.dart'
    as _i7;
import 'package:soloadventurer/features/sync/domain/entities/sync_entity_type.dart'
    as _i6;
import 'package:soloadventurer/features/sync/domain/models/sync_operation.dart'
    as _i3;
import 'package:soloadventurer/features/sync/domain/models/sync_status.dart'
    as _i4;
import 'package:soloadventurer/features/sync/domain/services/sync_service.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSyncQueueConfig_0 extends _i1.SmartFake
    implements _i2.SyncQueueConfig {
  _FakeSyncQueueConfig_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncResult_1 extends _i1.SmartFake implements _i2.SyncResult {
  _FakeSyncResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i2.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.SyncOperation> get queue => (super.noSuchMethod(
        Invocation.getter(#queue),
        returnValue: <_i3.SyncOperation>[],
      ) as List<_i3.SyncOperation>);

  @override
  int get queueSize => (super.noSuchMethod(
        Invocation.getter(#queueSize),
        returnValue: 0,
      ) as int);

  @override
  bool get isProcessing => (super.noSuchMethod(
        Invocation.getter(#isProcessing),
        returnValue: false,
      ) as bool);

  @override
  _i4.SyncOperationStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i4.SyncOperationStatus.idle,
      ) as _i4.SyncOperationStatus);

  @override
  _i5.Stream<_i4.SyncOperationStatus> get statusStream => (super.noSuchMethod(
        Invocation.getter(#statusStream),
        returnValue: _i5.Stream<_i4.SyncOperationStatus>.empty(),
      ) as _i5.Stream<_i4.SyncOperationStatus>);

  @override
  _i5.Stream<List<_i3.SyncOperation>> get queueStream => (super.noSuchMethod(
        Invocation.getter(#queueStream),
        returnValue: _i5.Stream<List<_i3.SyncOperation>>.empty(),
      ) as _i5.Stream<List<_i3.SyncOperation>>);

  @override
  _i2.SyncQueueConfig get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: _FakeSyncQueueConfig_0(
          this,
          Invocation.getter(#config),
        ),
      ) as _i2.SyncQueueConfig);

  @override
  _i5.Future<bool> enqueueOperation(_i3.SyncOperation? operation) =>
      (super.noSuchMethod(
        Invocation.method(
          #enqueueOperation,
          [operation],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> enqueueOperations(List<_i3.SyncOperation>? operations) =>
      (super.noSuchMethod(
        Invocation.method(
          #enqueueOperations,
          [operations],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<bool> removeOperation(String? operationId) => (super.noSuchMethod(
        Invocation.method(
          #removeOperation,
          [operationId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> clearQueue() => (super.noSuchMethod(
        Invocation.method(
          #clearQueue,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.SyncResult> processQueue() => (super.noSuchMethod(
        Invocation.method(
          #processQueue,
          [],
        ),
        returnValue: _i5.Future<_i2.SyncResult>.value(_FakeSyncResult_1(
          this,
          Invocation.method(
            #processQueue,
            [],
          ),
        )),
      ) as _i5.Future<_i2.SyncResult>);

  @override
  _i5.Future<_i2.SyncResult> processBatch({int? maxBatchSize}) =>
      (super.noSuchMethod(
        Invocation.method(
          #processBatch,
          [],
          {#maxBatchSize: maxBatchSize},
        ),
        returnValue: _i5.Future<_i2.SyncResult>.value(_FakeSyncResult_1(
          this,
          Invocation.method(
            #processBatch,
            [],
            {#maxBatchSize: maxBatchSize},
          ),
        )),
      ) as _i5.Future<_i2.SyncResult>);

  @override
  _i5.Future<int> retryFailedOperations() => (super.noSuchMethod(
        Invocation.method(
          #retryFailedOperations,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  List<_i3.SyncOperation> getOperationsByType(_i6.SyncEntityType? entityType) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOperationsByType,
          [entityType],
        ),
        returnValue: <_i3.SyncOperation>[],
      ) as List<_i3.SyncOperation>);

  @override
  List<_i3.SyncOperation> getOperationsByOperationType(
          _i3.SyncOperationType? operationType) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOperationsByOperationType,
          [operationType],
        ),
        returnValue: <_i3.SyncOperation>[],
      ) as List<_i3.SyncOperation>);

  @override
  List<_i3.SyncOperation> getOperationsForEntity(String? entityId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOperationsForEntity,
          [entityId],
        ),
        returnValue: <_i3.SyncOperation>[],
      ) as List<_i3.SyncOperation>);

  @override
  void pauseProcessing() => super.noSuchMethod(
        Invocation.method(
          #pauseProcessing,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resumeProcessing() => super.noSuchMethod(
        Invocation.method(
          #resumeProcessing,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateConfig(_i2.SyncQueueConfig? config) => super.noSuchMethod(
        Invocation.method(
          #updateConfig,
          [config],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LoggingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoggingService extends _i1.Mock implements _i7.LoggingService {
  MockLoggingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void logStateTransition({
    required String? feature,
    required String? fromState,
    required String? toState,
    Map<String, dynamic>? metadata,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logStateTransition,
          [],
          {
            #feature: feature,
            #fromState: fromState,
            #toState: toState,
            #metadata: metadata,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logError({
    required String? feature,
    required String? error,
    String? code,
    Map<String, dynamic>? metadata,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logError,
          [],
          {
            #feature: feature,
            #error: error,
            #code: code,
            #metadata: metadata,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logAuthEvent({
    required String? event,
    required String? status,
    Map<String, dynamic>? metadata,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logAuthEvent,
          [],
          {
            #event: event,
            #status: status,
            #metadata: metadata,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logTokenEvent({
    required String? event,
    required String? status,
    Map<String, dynamic>? metadata,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logTokenEvent,
          [],
          {
            #event: event,
            #status: status,
            #metadata: metadata,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logTokenRotation({
    required Object? oldSession,
    required Object? newSession,
    String? reason,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logTokenRotation,
          [],
          {
            #oldSession: oldSession,
            #newSession: newSession,
            #reason: reason,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logTokenBlacklist({
    required String? token,
    required String? reason,
    DateTime? expiryTime,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logTokenBlacklist,
          [],
          {
            #token: token,
            #reason: reason,
            #expiryTime: expiryTime,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logTokenRefresh({
    required bool? success,
    String? error,
    int? attemptNumber = 1,
    Map<String, dynamic>? additionalInfo,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logTokenRefresh,
          [],
          {
            #success: success,
            #error: error,
            #attemptNumber: attemptNumber,
            #additionalInfo: additionalInfo,
          },
        ),
        returnValueForMissingStub: null,
      );
}
